import type { Feature, Article } from './types';

const NOW = new Date().toISOString();

export const MOCK_FEATURES: Feature[] = [
  {
    id: 'love-01',
    title: '愛を引き寄せる月の引力',
    category: 'love',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'money-01',
    title: '豊かさを解放するリセット術',
    category: 'money',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'family-01',
    title: '家族の絆を深める夏至の智慧',
    category: 'family',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'body-01',
    title: '身体と対話する内なる声',
    category: 'body',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'art-love-01',
    title: '満月の夜に告白すべき理由',
    category: 'love',
    featureId: 'love-01',
    body: '<p>満月は感情のエネルギーが頂点に達する瞬間。長い間心の中で育ててきた気持ちを言葉にするなら、このタイミングが最も自然です。</p><p>月の引力は海の潮を動かすように、私たちの感情にも働きかけています。勇気を出した一歩が、大きな変化の始まりになるでしょう。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-love-02',
    title: '引き寄せを加速する言葉の使い方',
    category: 'love',
    featureId: 'love-01',
    body: '<p>言葉は思考を形にする最初の器。ネガティブな否定語を取り除き、すでに実現しているかのように語ることが現実創造の鍵です。</p><h2>今日からできる３つの言い換え</h2><p>「どうせ」を「今はまだ」に。「でも」を「そして」に。「忙しい」を「充実している」に変えるだけで、世界の見え方が変わります。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-money-01',
    title: '金星期に投資を始めるタイミング',
    category: 'money',
    featureId: 'money-01',
    body: '<p>金星が順行しているとき、豊かさのエネルギーは外向きに流れます。このサイクルを意識した資産形成は、西洋占星術でも長く語られてきた智慧です。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-family-01',
    title: '家族の星座バランスを読む',
    category: 'family',
    featureId: 'family-01',
    body: '<p>家族それぞれの月のサインを知ることで、感情の反応パターンが見えてきます。衝突の背後にある「違い」を「補完関係」として捉え直すと、関係性が大きく変わります。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-body-01',
    title: '月の満ち欠けとデトックス',
    category: 'body',
    featureId: 'body-01',
    body: '<p>新月から満月にかけては蓄積のフェーズ。満月から新月にかけては解放のフェーズです。デトックスや断食は下弦の月前後が最も効果的と言われています。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
];
