import type { Feature, Article } from './types';

const NOW = new Date().toISOString();

export const MOCK_FEATURES: Feature[] = [
  {
    id: 'love-01',
    title: '愛を引き寄せる月の引力',
    category: 'love',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'money-01',
    title: '豊かさを解放するリセット術',
    category: 'money',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'family-01',
    title: '家族の絆を深める夏至の智慧',
    category: 'family',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'body-01',
    title: '身体と対話する内なる声',
    category: 'body',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'spirit-01',
    title: '毎朝1分の浄化習慣で開運体質になる',
    category: 'spirit',
    subtitle: '2025年7月号',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'art-love-01',
    title: '満月の夜に告白すべき理由',
    category: 'love',
    featureId: 'love-01',
    body: '<p>満月は感情のエネルギーが頂点に達する瞬間。長い間心の中で育ててきた気持ちを言葉にするなら、このタイミングが最も自然です。</p><p>月の引力は海の潮を動かすように、私たちの感情にも働きかけています。勇気を出した一歩が、大きな変化の始まりになるでしょう。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-love-02',
    title: '引き寄せを加速する言葉の使い方',
    category: 'love',
    featureId: 'love-01',
    body: '<p>言葉は思考を形にする最初の器。ネガティブな否定語を取り除き、すでに実現しているかのように語ることが現実創造の鍵です。</p><h2>今日からできる３つの言い換え</h2><p>「どうせ」を「今はまだ」に。「でも」を「そして」に。「忙しい」を「充実している」に変えるだけで、世界の見え方が変わります。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-money-01',
    title: '金星期に投資を始めるタイミング',
    category: 'money',
    featureId: 'money-01',
    body: '<p>金星が順行しているとき、豊かさのエネルギーは外向きに流れます。このサイクルを意識した資産形成は、西洋占星術でも長く語られてきた智慧です。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-money-02',
    title: '金運が上がる人の財布に共通する、たった3つの習慣',
    category: 'money',
    featureId: 'money-01',
    body: '<p>お金は「巡り」を嫌う人のところには留まりません。金運が良いと言われる人の財布を見ると、レシートやポイントカードが溜め込まれておらず、驚くほどすっきりしています。</p><h2>今日からできる3つの習慣</h2><p>1つ目は、レシートをその日のうちに抜くこと。2つ目は、お札の向きを揃えて入れること。3つ目は、新月の日に財布の中身を一度空にして休ませてあげることです。</p><p>財布は「お金の家」。居心地の良い家には、また戻ってきたくなるものです。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-family-01',
    title: '家族の星座バランスを読む',
    category: 'family',
    featureId: 'family-01',
    body: '<p>家族それぞれの月のサインを知ることで、感情の反応パターンが見えてきます。衝突の背後にある「違い」を「補完関係」として捉え直すと、関係性が大きく変わります。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-body-01',
    title: '月の満ち欠けとデトックス',
    category: 'body',
    featureId: 'body-01',
    body: '<p>新月から満月にかけては蓄積のフェーズ。満月から新月にかけては解放のフェーズです。デトックスや断食は下弦の月前後が最も効果的と言われています。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-spirit-01',
    title: '開運は特別な日じゃなくていい。毎朝1分の浄化習慣',
    category: 'spirit',
    featureId: 'spirit-01',
    body: '<p>開運というと特別な儀式を想像しがちですが、実は「毎日続けられる小さな習慣」の方が体質そのものを変えていきます。</p><h2>朝1分でできる浄化ルーティン</h2><p>カーテンを開けて朝日を浴びながら、深呼吸を3回。手のひらを太陽に向けて「今日も良い流れに乗る」と心の中で唱えるだけ。たったこれだけで、その日一日の気の巡りが変わります。</p><p>まいスピの毎朝の運気診断と合わせて続けることで、自分の変化により気づきやすくなるはずです。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
  {
    id: 'art-spirit-02',
    title: '「なんとなく調子が悪い日」に効く、塩と水の浄化法',
    category: 'spirit',
    featureId: 'spirit-01',
    body: '<p>理由もなく気分が晴れない日は、環境のエネルギーが滞っているサインかもしれません。そんな日は難しく考えず、塩と水を使った昔ながらの浄化法を試してみてください。</p><p>コップ一杯の水に天然塩をひとつまみ溶かし、部屋の四隅に少しずつ置く。それだけで空間の空気が変わったように感じられるはずです。</p><p>大切なのは完璧にやることではなく、「整えよう」と意図すること自体が運気を上向かせるということです。</p>',
    createdAt: NOW,
    updatedAt: NOW,
    publishedAt: NOW,
    revisedAt: NOW,
  },
];
